apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: nsus-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: nsus-ebs
