apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-controller
  namespace: argocd
spec:
  sources:
    - repoURL: "https://aws.github.io/eks-charts"
      targetRevision: HEAD
      chart: aws-load-balancer-controller
      # helm:
      #   valueFiles:
      #     - ../apps/ingress-nginx.yaml
  destination:
    namespace: default
    server: "https://kubernetes.default.svc"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
