apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mysql
    targetRevision: "9.19.1"
    helm:
      parameters:
        - name: "auth.username"
          value: "root"
        - name: "auth.rootPassword"
          value: "1234"
        - name: "auth.database"
          value: "order"
        - name: "primary.command"
          value:
            - --character-set-server=utf8
            - --collation-server=utf8_general_ci

  destination:
    namespace: default
    server: "https://kubernetes.default.svc"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
